name: CD — Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # clonar o actualizar el repo
            if [ -d "TrabajoPract7MLOPS" ]; then
              cd TrabajoPract7MLOPS && git pull origin main
            else
              git clone https://github.com/Susyherfo/TrabajoPract7MLOPS.git
              cd TrabajoPract7MLOPS
            fi

            # detener contenedor anterior si existe
            docker stop mlops-app || true
            docker rm mlops-app || true

            # buildear imagen nueva
            docker build -t mlops-app .

            # correr el contenedor
            docker run -d \
              --name mlops-app \
              --restart always \
              -p 8000:8000 \
              -e AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }} \
              -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
              mlops-app

            # verificar que quedó corriendo
            docker ps | grep mlops-app